Створіть одновимірний масив (вектор) із геометричною прогресією, де кожне
наступне число менше попереднього в 3 рази, починаючи з 81, та виведіть його
значення

In [2]:
import numpy as np

start_value = 81
ratio = 1/3
num_elements = 6

geometric_progression = start_value * ratio**np.arange(num_elements)

print("Масив із геометричною прогресією:")
print(geometric_progression)


Масив із геометричною прогресією:
[81.         27.          9.          3.          1.          0.33333333]


Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його оберненими
значеннями дробових частин від ділення кожного числа на 2, починаючи з 1, та
виведіть його значення.

In [5]:
import numpy as np

matrix = np.zeros((3, 3))

for i in range(3):
    for j in range(3):
        num = i * 3 + j + 1
        fraction = (num / 2) - (num // 2)
        if fraction != 0:
            matrix[i, j] = 1 / fraction
        else:
            matrix[i, j] = 0

print(matrix)


[[2. 0. 2.]
 [0. 2. 0.]
 [2. 0. 2.]]


Створіть масив розміром 4x4, заповніть його випадковими натуральними числами від
1 до 10 і знайдіть мін елемент.

In [6]:
import numpy as np

array = np.random.randint(1, 11, size=(4, 4))

min_element = np.min(array)

print("Масив:")
print(array)
print("Мінімальний елемент:", min_element)


Масив:
[[ 8  3  5  2]
 [ 3  9  6 10]
 [ 8  6  9  8]
 [ 3  8  9  6]]
Мінімальний елемент: 2


Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть середнє арифметичне елементів, розташованих на
побічній діагоналі.

In [7]:
import numpy as np

array = np.random.rand(5, 5)

side_diagonal_elements = [array[i, 4 - i] for i in range(5)]

mean_side_diagonal = np.mean(side_diagonal_elements)

print("Масив:")
print(array)
print("Елементи на побічній діагоналі:", side_diagonal_elements)
print("Середнє арифметичне елементів на побічній діагоналі:", mean_side_diagonal)


Масив:
[[0.1091097  0.59031652 0.14564208 0.35327426 0.83485997]
 [0.70292362 0.43824895 0.15682864 0.11168925 0.52985744]
 [0.6676334  0.40373794 0.63638153 0.46471072 0.98245252]
 [0.22516532 0.51491938 0.77699194 0.81171919 0.33227834]
 [0.7605887  0.32643736 0.01304339 0.60154797 0.80848932]]
Елементи на побічній діагоналі: [0.8348599686522848, 0.11168925217941039, 0.636381534125568, 0.5149193774157372, 0.7605887022825533]
Середнє арифметичне елементів на побічній діагоналі: 0.5716877669311107


Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими
числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання,
віднімання та множення.

In [8]:
import numpy as np

array1 = np.random.randint(1, 21, size=5)
array2 = np.random.randint(1, 21, size=5)

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("Масив 1:", array1)
print("Масив 2:", array2)
print("Додавання:", addition)
print("Віднімання:", subtraction)
print("Множення:", multiplication)


Масив 1: [ 5 19  4  1 15]
Масив 2: [ 7  8 19  5 16]
Додавання: [12 27 23  6 31]
Віднімання: [ -2  11 -15  -4  -1]
Множення: [ 35 152  76   5 240]


Створіть дві матриці 3x3, заповніть їх довільними цілими числами від -5 до 5 та
знайдіть їх добуток.


In [9]:
import numpy as np

matrix1 = np.random.randint(-5, 6, size=(3, 3))
matrix2 = np.random.randint(-5, 6, size=(3, 3))

product = np.dot(matrix1, matrix2)

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)
print("Добуток матриць:")
print(product)


Матриця 1:
[[-5 -3 -3]
 [ 3 -3 -1]
 [-1  4 -3]]
Матриця 2:
[[ 1 -2 -1]
 [-4 -4  3]
 [ 5 -4 -2]]
Добуток матриць:
[[ -8  34   2]
 [ 10  10 -10]
 [-32  -2  19]]


Створіть дві матриці розміром 2x3 та 3x4, заповніть їх випадковими цілими числами
в діапазоні від 1 до 5 та перемножте їх між собою.

In [10]:
import numpy as np

matrix1 = np.random.randint(1, 6, size=(2, 3))

matrix2 = np.random.randint(1, 6, size=(3, 4))

product = np.dot(matrix1, matrix2)

print("Матриця 1 (2x3):")
print(matrix1)
print("Матриця 2 (3x4):")
print(matrix2)
print("Добуток матриць (2x4):")
print(product)


Матриця 1 (2x3):
[[1 3 4]
 [5 2 5]]
Матриця 2 (3x4):
[[1 4 4 2]
 [1 1 3 2]
 [2 3 5 4]]
Добуток матриць (2x4):
[[12 19 33 24]
 [17 37 51 34]]


Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 10 та знайдіть її обернену матрицю.

In [11]:
import numpy as np

matrix = np.random.randint(1, 11, size=(3, 3))

if np.linalg.det(matrix) == 0:
    print("Матриця не є оберненою (визначник дорівнює нулю).")
else:
    inverse_matrix = np.linalg.inv(matrix)
    print("Матриця:")
    print(matrix)
    print("Обернена матриця:")
    print(inverse_matrix)


Матриця:
[[ 6  4  1]
 [ 4  5 10]
 [ 9 10  8]]
Обернена матриця:
[[ 0.45112782  0.16541353 -0.26315789]
 [-0.43609023 -0.29323308  0.42105263]
 [ 0.03759398  0.18045113 -0.10526316]]


Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в
діапазоні від 0 до 1 та транспонуйте її

In [12]:
import numpy as np

matrix = np.random.rand(4, 4)

transposed_matrix = np.transpose(matrix)

print("Оригінальна матриця:")
print(matrix)
print("Транспонована матриця:")
print(transposed_matrix)


Оригінальна матриця:
[[0.47851607 0.96427448 0.33309103 0.98029095]
 [0.71627313 0.08461266 0.76682897 0.80770389]
 [0.36628159 0.81103512 0.9655516  0.72296778]
 [0.30590503 0.14355363 0.14978365 0.23157029]]
Транспонована матриця:
[[0.47851607 0.71627313 0.36628159 0.30590503]
 [0.96427448 0.08461266 0.81103512 0.14355363]
 [0.33309103 0.76682897 0.9655516  0.14978365]
 [0.98029095 0.80770389 0.72296778 0.23157029]]


Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
від 0 до 1, і знайдіть добуток матриці на вектор

In [13]:
import numpy as np

matrix = np.random.rand(3, 4)

vector = np.random.rand(4, 1)

product = np.dot(matrix, vector)

print("Матриця (3x4):")
print(matrix)
print("Вектор (4x1):")
print(vector)
print("Добуток матриці на вектор (3x1):")
print(product)


Матриця (3x4):
[[0.34010288 0.51438969 0.51416808 0.02622685]
 [0.65440794 0.8592814  0.64641052 0.57703623]
 [0.65551844 0.94592703 0.71084897 0.23137018]]
Вектор (4x1):
[[0.25876379]
 [0.68952203]
 [0.77556998]
 [0.6226586 ]]
Добуток матриці на вектор (3x1):
[[0.85779304]
 [1.6224637 ]
 [1.51723972]]


Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в
діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [14]:
import numpy as np

matrix = np.random.rand(2, 3)

vector = np.random.randint(1, 11, size=(3, 1))

product = np.dot(matrix, vector)

print("Матриця (2x3):")
print(matrix)
print("Вектор (3x1):")
print(vector)
print("Добуток матриці на вектор (2x1):")
print(product)


Матриця (2x3):
[[0.56683266 0.19731978 0.9969193 ]
 [0.80461457 0.05579862 0.36693385]]
Вектор (3x1):
[[ 4]
 [ 1]
 [10]]
Добуток матриці на вектор (2x1):
[[12.43384341]
 [ 6.9435954 ]]


Створіть дві матриці розміром 7x7, заповніть їх випадковими цілими числами в
діапазоні від 1 до 10 та знайдіть їхню різницю.

In [15]:
import numpy as np

matrix1 = np.random.randint(1, 11, size=(7, 7))
matrix2 = np.random.randint(1, 11, size=(7, 7))

difference = matrix1 - matrix2

print("Матриця 1 (7x7):")
print(matrix1)
print("Матриця 2 (7x7):")
print(matrix2)
print("Різниця матриць (7x7):")
print(difference)


Матриця 1 (7x7):
[[ 6  2  9  8  1  9  8]
 [10 10 10  8  7  4  1]
 [ 3  4 10  4  8  6  2]
 [ 3  3  5 10  4  9  1]
 [ 5  9  4 10  4  5  2]
 [ 8  8  6  2  4  9  1]
 [ 7  8  6  3  5  7  5]]
Матриця 2 (7x7):
[[ 4  1  6  5  9  8  1]
 [ 4  7  4 10  5  7  3]
 [ 3 10  2  8  8  2  3]
 [ 7  3  3  5  6  8  3]
 [ 7  5  9  4  4  4  6]
 [ 2  8  6  7  4  7  3]
 [ 5  3  3  6  1  4 10]]
Різниця матриць (7x7):
[[ 2  1  3  3 -8  1  7]
 [ 6  3  6 -2  2 -3 -2]
 [ 0 -6  8 -4  0  4 -1]
 [-4  0  2  5 -2  1 -2]
 [-2  4 -5  6  0  1 -4]
 [ 6  0  0 -5  0  2 -2]
 [ 2  5  3 -3  4  3 -5]]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в
діапазоні від -5 до 5 та знайдіть суму їх елементів

In [16]:
import numpy as np

matrix1 = np.random.randint(-5, 6, size=(2, 2))
matrix2 = np.random.randint(-5, 6, size=(2, 2))

sum_matrix1 = np.sum(matrix1)
sum_matrix2 = np.sum(matrix2)

print("Матриця 1 (2x2):")
print(matrix1)
print("Сума елементів матриці 1:", sum_matrix1)

print("Матриця 2 (2x2):")
print(matrix2)
print("Сума елементів матриці 2:", sum_matrix2)


Матриця 1 (2x2):
[[-3  1]
 [-5 -2]]
Сума елементів матриці 1: -9
Матриця 2 (2x2):
[[-4 -1]
 [-5  0]]
Сума елементів матриці 2: -10


Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 10 та знайдіть добуток елементів матриці, які менше за їх середнє
арифметичне значення.

In [17]:
import numpy as np

matrix = np.random.randint(1, 11, size=(3, 3))

mean_value = np.mean(matrix)

elements_less_than_mean = matrix[matrix < mean_value]

if len(elements_less_than_mean) > 0:
    product = np.prod(elements_less_than_mean)
else:
    product = None

print("Матриця (3x3):")
print(matrix)
print("Середнє арифметичне:", mean_value)
print("Елементи менше середнього арифметичного:", elements_less_than_mean)
print("Добуток елементів менше середнього арифметичного:", product)


Матриця (3x3):
[[ 7  3  7]
 [ 9  9  9]
 [ 5  5 10]]
Середнє арифметичне: 7.111111111111111
Елементи менше середнього арифметичного: [7 3 7 5 5]
Добуток елементів менше середнього арифметичного: 3675


Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить найбільше ціле значення
в кожному рядку матриці

In [18]:
import numpy as np

matrix = np.random.uniform(-1, 1, size=(3, 3))

def max_integer_in_row(row):
    integers = np.floor(row).astype(int)
    return np.max(integers)

max_integers = np.array([max_integer_in_row(row) for row in matrix])

print("Матриця (3x3):")
print(matrix)
print("Вектор-стовпчик з найбільшими цілими значеннями в кожному рядку:")
print(max_integers)


Матриця (3x3):
[[ 0.48563162 -0.54264181  0.1433376 ]
 [-0.68818922  0.96524792 -0.72545343]
 [-0.84482483 -0.71570901  0.74407464]]
Вектор-стовпчик з найбільшими цілими значеннями в кожному рядку:
[0 0 0]


Висновок: У цій лабораторній роботі було виконано ряд завдань для роботи з масивами та матрицями за допомогою бібліотеки NumPy в Python.
